### ISSUE TITLE
Use "mediafinder" instead of "imageupload"

### ISSUE THREAD

**Issue by gpluess** [SaifurRahmanMohsin/Carousel-Plugin#12]
Hi, I'd like to select images from my media library instead of uploading new ones. Is that possible?

**Comment by mohsin** [comment]
Unfortunately, OctoberCMS doesn't provide a component that allows the selection between the two. Otherwise, I'd have incorporated that instead. Ideally, there should be a way by which user can select between Media Finder or File Upload and proceed to uploading their file. I hope OctoberCMS team provides a mechanism for that soon and I'll surely add that in the plugin.

**Comment by gpluess** [comment]
Thanks for the quick reply!

I tried the following:
Replacing `fileupload` with `mediafinder` in `models/carousel/fields.yaml` which surprisingly worked without any problems. I am able to select the images directly from the media library. The same goes for the frontend: the carousel is displayed correctly. However, when I try to **update** the  carousel in the backend, an error is thrown. I'll follow up with the exact error message as soon as I am at my computer at home.

**Comment by gpluess** [comment]
Ok, here's the exact error message:

```
trim() expects parameter 1 to be string, array given

/path/to/my/project/modules/system/Classes/MediaLibrary.php line 445
```

**Comment by mohsin** [comment]
You can't do this at this point.

1. The mediafinder doesn't allow you to select multiple images. This is a feature that [has been pending](https://github.com/octobercms/october/issues/1658) for quite a while and OctoberCMS team hasn't done it yet.

2. It's incorrect for you to edit the plugin from the code like that. When I push an update to the plugin it will overwrite your changes. The way you can update plugins is by either overriding the partials or expanding the plugin component in-code and re-writing it.

3. Your method fails because you had already saved the images using the fileupload widget and then changed to mediafinder. So when you try to load the mediafinder component it throws an error.

4. Even if you clean the table and switch to mediafinder it won't work because mediafinder stores a single string of the path of the selected media file whereas this plugin uses an attachMany relationship to store multiple images. The fileUpload and mediafinder widgets are highly incompatible because of this.

5. I wouldn't push an update for this due to the limitations it presents. The mediafinder isn't good enough and until there's a solution as I suggested in my previous comment to select between the two it doesn't make sense for me to change the plugin to use a single-item only mediafinder widget. There is [an issue open](https://github.com/octobercms/october/issues/2896) that's for fixing this but it's been over a year with no progress. Once it's ready I'd update the plugin first thing to use the new widget that lets me select between media and fileupload.

**Comment by mohsin** [comment]
Check out [the new branch](https://github.com/SaifurRahmanMohsin/Carousel-Plugin/tree/mediafinder-version) that I pushed now. It's just to demonstrate how this plugin would work using the mediafinder plugin. To test it, download that branch code and replace your plugin folder with that code. Sign out and sign into the backend or from terminal/command run `php artisan october:up` in the OctoberCMS project directory.

In your CMS section, add the `carousel` component and then remove the component tag alone leaving the component attached to your page. Use this code:
```
    <div id="carousel-{{ carousel.id }}" class="carousel slide" data-ride="carousel">
        <img src="{{ carousel.carousel.image|media }}">
    </div>
```

You should be able to see the image appear on the page.

**Comment by gpluess** [comment]
Thank you very much for explaining!
